server:
  port: 80
logging:
  level:
    com.zte: info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
mybatis:
  #configuration:
    #map-underscore-to-camel-case: true
  #mapper-locations: mapper/*.xml
  type-aliases-package: com.zte.pojo